package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{

    private final DaoConfig noteTableDaoConfig;
    private final DaoConfig loreDetailTableDaoConfig;

    private final NoteTableDao noteTableDao;
    private final LoreDetailTableDao loreDetailTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap)
    {
        super(db);

        noteTableDaoConfig = daoConfigMap.get(NoteTableDao.class).clone();
        noteTableDaoConfig.initIdentityScope(type);

        loreDetailTableDaoConfig = daoConfigMap.get(LoreDetailTableDao.class).clone();
        loreDetailTableDaoConfig.initIdentityScope(type);

        noteTableDao = new NoteTableDao(noteTableDaoConfig, this);
        loreDetailTableDao = new LoreDetailTableDao(loreDetailTableDaoConfig, this);

        registerDao(NoteTable.class, noteTableDao);
        registerDao(LoreDetailTable.class, loreDetailTableDao);
    }

    public void clear()
    {
        noteTableDaoConfig.getIdentityScope().clear();
        loreDetailTableDaoConfig.getIdentityScope().clear();
    }

    public NoteTableDao getNoteTableDao()
    {
        return noteTableDao;
    }

    public LoreDetailTableDao getLoreDetailTableDao()
    {
        return loreDetailTableDao;
    }

}
